### ISSUE TITLE
Process Specification and delayed start

### ISSUE THREAD

**Issue by whitmo** [michelp/nerve#6]
We need a simple way of specify information for executing a process. 

Proposal in yaml (could just as easily be json or any serializable mapping).

``` yaml
defaults:
  endpoint: none
  recv_in: false
  send_out: false
  send_err: false
  send_all: true
  hangout: false
  restart_retries: 3
  autorestart: false
  startsecs: 1
  exitcodes: [0, 2]
  poll_interval: 0.1
  ping_interval: 1
  wait_to_die: 3
  linger: 0

tp:
  numprocs: 3
  procname: '{name}:{hostname}:{procnum}'
  cmd: zvr tp --id={procnum}

```

Defaults are optional and `default` is a special key in a specification.  A
